# Generated by Django 5.2.1 on 2025-07-01 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document_processor', '0006_alter_document_originality_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('paraphrased_text', models.TextField()),
                ('citation_text', models.TextField()),
                ('source_url', models.URLField(max_length=512)),
                ('source_title', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='document_processor.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
