#!/usr/bin/env node

/**
 * This script generates an env-config.js file in the public directory
 * that makes environment variables available at runtime via window.env
 */

import { writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

// Get the current file's directory
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Define the target file path
const targetPath = resolve(__dirname, '../public/env-config.js');

// Get environment variables or use defaults from the existing env-config.js if available
let currentApiKey = 'AIzaSyDI2WWBcVC3KO1enuXL9u7NEI-CjsT6gHA';
let currentSearchEngineId = '4011e6edae3354b9e';

// Get environment variables if available
const googleApiKey = process.env.VITE_GOOGLE_API_KEY || 
                    process.env.REACT_APP_GOOGLE_API_KEY || 
                    currentApiKey;

const searchEngineId = process.env.VITE_GOOGLE_SEARCH_ENGINE_ID || 
                      process.env.REACT_APP_GOOGLE_SEARCH_ENGINE_ID || 
                      currentSearchEngineId;

// Generate the environment configuration content
const envConfigContent = `// This file is generated - DO NOT EDIT!
// The file is generated by scripts/set-env.js

window.env = {
  // Google API configuration
  REACT_APP_GOOGLE_API_KEY: '${googleApiKey}',
  REACT_APP_GOOGLE_SEARCH_ENGINE_ID: '${searchEngineId}',
};
`;

// Write the content to the file
writeFileSync(targetPath, envConfigContent);

console.log(`Environment configuration generated at ${targetPath}`);
console.log(`Using API Key: ${googleApiKey.substring(0, 5)}...${googleApiKey.substring(googleApiKey.length - 4)}`);
console.log(`Using Search Engine ID: ${searchEngineId.substring(0, 5)}...${searchEngineId.substring(searchEngineId.length - 4)}`); 