# Generated by Django 5.2.1 on 2025-05-29 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0003_document_original_filename_alter_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
    ]
