# Generated by Django 5.2.1 on 2025-06-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0004_remove_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='originality_score',
            field=models.FloatField(default=100.0),
        ),
    ]
