# Generated by Django 5.2.1 on 2025-06-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0005_document_originality_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='originality_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
